# Generated by Django 5.0.1 on 2024-02-04 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='motos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('marca', models.CharField(choices=[('honda', 'honda'), ('bajaj', 'bajaj'), ('yamaha', 'yamaha'), ('ktm', 'ktm'), ('bmw', 'bmw'), ('otro', 'otro')], default='honda', max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('cilindrada', models.IntegerField()),
                ('kilometro', models.IntegerField()),
                ('color', models.CharField(max_length=80)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9)),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('publicacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
