# Generated by Django 5.0.1 on 2024-02-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
